title: Asfalto Ascari
logo: '/images/Logo4eWhite.png'
description: WIP
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Asfalto Ascari
  image: '/images/Logo4eWhite.png'

# Contact links
# Example of adding a new link to the footer - {name: "Github", icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
- {name: "Twitter", icon: "ion-logo-twitter", link: "https://twitter.com/AsfaltoAscari"}
- {name: "Facebook", icon: "ion-logo-facebook", link: "https://www.facebook.com/AsfaltoAscari"}
#- {name: "Dribbble", icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {name: "Instagram", icon: "ion-logo-instagram", link: "https://www.instagram.com/asfaltoascari/"}
# - {name: "Pinterest", icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {name: "Email", icon: "ion-ios-mail", link: "mailto:mediarelations@asfaltoascari.com"}

# Slider Section
slider: Headlines # NOTE - By default, the slider is set to display tags. Now the slider shows the tag with the text "Life". If you do not want to use the slider, leave the slider field empty.

# Comment Section (Disqus)
disqus-identifier: asfaltoascari

# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: https://www.instagram.com/asfaltoascari/
userID: 6716400487
accessToken: 6716400487.1677ed0.4fae51c47bc544a895b81756a7d0c477

# Google Analytics
google-analytics: UA-149505541-1

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
