title: Asfalto Ascari
logo: '/images/WebDesign/PNG/AsfaltoAscariLogo1K_WT.png'
description: Formula 1™ and Motorsports Community - Broadcast Media, Racing and Discussion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Asfalto Ascari
  image: '/images/Logo4eWhite.png'

# Contact links
# Example of adding a new link to the footer - {name: "Github", icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
contact:
- {name: "Twitter", icon: "ion-logo-twitter", link: "https://twitter.com/AsfaltoAscari"}
- {name: "Facebook", icon: "ion-logo-facebook", link: "https://www.facebook.com/AsfaltoAscari"}
#- {name: "Dribbble", icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {name: "Instagram", icon: "ion-logo-instagram", link: "https://www.instagram.com/asfaltoascari/"}
# - {name: "Pinterest", icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {name: "Email", icon: "ion-md-send", link: "mailto:mediarelations@asfaltoascari.com"}
- {name: "Corporate", icon: "ion-md-business", link: "https://corporate.asfaltoascari.com"}

# Slider Section
slider: Headlines # NOTE - By default, the slider is set to display tags. Now the slider shows the tag with the text "Life". If you do not want to use the slider, This is due to change, leave the slider field empty.

# Comment Section (Disqus)
disqus-identifier: asfaltoascari

# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: https://www.instagram.com/asfaltoascari/
userID: 21505954693
accessToken: 21505954693.12ee5e7.3744658025b34fb79a6f383cc1e309e7

# Google Analytics
google-analytics: UA-149505541-1

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-compress-images
  - jekyll-language-plugin
  - jekyll-seo-tag
  - github-pages-health-check

paginate: 15
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  none

sass:
  sass_dir: _sass
  style: compressed

  # Plugin cmd & others
